version: '3.8'

services:
  dns_server:
    image: ubuntu/bind9:9.16-20.04_beta
    container_name: dns-server-compose
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config/named.conf.local:/etc/bind/named.conf.local:ro
      - ./zones:/var/lib/bind:ro